version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_pod
      POSTGRES_PASSWORD: "uPADQR6UMpAuhA2op8ZFCojojMZ1Er1B"
    volumes:
      - test_pod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "qBUUpGB7XWf2UXfnrFYd8ywSq0mblKR5"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  test_pod_data:
